from nose.tools import assert_equal
from rogalik.board import Board
from rogalik.monster import Orc
from rogalik.player import Player


def test_render():
    board = Board(20, 20)
    board.add_mob(Orc(), 5, 6)
    board.add_mob(Player(), 15, 17)
    rendering = board.render()
    assert_equal(rendering, """....................
....................
....................
....................
....................
....................
.....o..............
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
...............@....
....................
....................""")


def test_move():
    board = Board(20, 20)
    o = Orc()
    board.add_mob(o, 5, 6)
    board.move((5, 6), (-1, 1))
    assert_equal(board.mobs[4, 7], o)
